# Generated by Django 4.2 on 2023-12-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
