# Generated by Django 4.2.2 on 2024-02-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_alter_follower_id_alter_like_id_alter_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
    ]
