# Generated by Django 4.2.2 on 2024-02-03 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_rename_user_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followed",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_who_is_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="follower",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_who_follows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
